### ISSUE TITLE
almost perfect solution found

### ISSUE THREAD

**Issue by klx3300** [recolic/dingtalk-wine-2019#1]
1. run everything using WINEARCH=win32
2. copy 32-bit riched20.dll & msftedit.dll from Windows 7 (or from Google)
3. configure library override in winecfg (more specific, riched20 & msftedit change to native)
4. everything works, screen shot & CJK character display in input box

only bug now: cannot use input method in input box. (Guessed this require extensive support from riched20.dll, but obviously M$ won't do that.)

**Comment by recolic** [comment]
update wineHQ AppDB please
  
  
  

  
  
  
  
  
>
